// inscripcionesMock.js - inscripciones falsas para simular datos del backend

export const INSCRIPCIONES_MOCK = [
    {
        id: 1,
        nombreAlumno:    "Lucas Rodríguez",
        dniAlumno:       "48.220.101",
        actividad:       "Natación",
        sede:            "Capilla San José Obrero",
        nombreAdulto:    "Ana Rodríguez",
        telefonoAdulto:  "11 3456-7890",
        fechaInscripcion:"20/05/2026",
        estado:          "CONFIRMADO",
    },
    {
        id: 2,
        nombreAlumno:    "Sofía Farías",
        dniAlumno:       "49.103.882",
        actividad:       "Folklore",
        sede:            "Capilla San José Obrero",
        nombreAdulto:    "Jorge Farías",
        telefonoAdulto:  "11 4567-8901",
        fechaInscripcion:"19/05/2026",
        estado:          "PENDIENTE",
    },
    {
        id: 3,
        nombreAlumno:    "Tomás Méndez",
        dniAlumno:       "50.008.441",
        actividad:       "Fútbol juvenil",
        sede:            "Cancha de Manco",
        nombreAdulto:    "Claudia Méndez",
        telefonoAdulto:  "11 5678-9012",
        fechaInscripcion:"18/05/2026",
        estado:          "CONFIRMADO",
    },
    {
        id: 4,
        nombreAlumno:    "Valentina Paz",
        dniAlumno:       "51.440.229",
        actividad:       "Básquet",
        sede:            "Parroquia Sagrado Corazón",
        nombreAdulto:    "Roberto Paz",
        telefonoAdulto:  "11 6789-0123",
        fechaInscripcion:"17/05/2026",
        estado:          "REVISION",
    },
    {
        id: 5,
        nombreAlumno:    "Martina García",
        dniAlumno:       "49.103.883",
        actividad:       "Hockey mixto",
        sede:            "Capilla San José Obrero",
        nombreAdulto:    "Laura García",
        telefonoAdulto:  "11 7890-1234",
        fechaInscripcion:"16/05/2026",
        estado:          "CONFIRMADO",
    },
    {
        id: 6,
        nombreAlumno:    "Nicolás Torres",
        dniAlumno:       "52.001.334",
        actividad:       "Taekwondo",
        sede:            "Capilla San José Obrero",
        nombreAdulto:    "María Torres",
        telefonoAdulto:  "11 8901-2345",
        fechaInscripcion:"15/05/2026",
        estado:          "PENDIENTE",
    },
]

export const STATS_MOCK = {
    totalAlumnos:      148,
    actividadesActivas: 7,
    cuposDisponibles:   34,
    pendientes:          6,
}