// inscripcionesMock.js - inscripciones falsas para simular datos del backend

export const INSCRIPCIONES_MOCK = [
    {
        id: 1,
        nombreAlumno:    "Lucas Rodríguez",
        dniAlumno:       "48.220.101",
        actividad:       "Natación",
        sede:            "Capilla San José Obrero",
        nombreAdulto:    "Ana Rodríguez",
        telefonoAdulto:  "11 3456-7890",
        fechaInscripcion:"20/05/2026",
        estado:          "CONFIRMADO",
    },
    {
        id: 2,
        nombreAlumno:    "Sofía Farías",
        dniAlumno:       "49.103.882",
        actividad:       "Folklore",
        sede:            "Capilla San José Obrero",
        nombreAdulto:    "Jorge Farías",
        telefonoAdulto:  "11 4567-8901",
        fechaInscripcion:"19/05/2026",
        estado:          "PENDIENTE",
    },
    {
        id: 3,
        nombreAlumno:    "Tomás Méndez",
        dniAlumno:       "50.008.441",
        actividad:       "Fútbol juvenil",
        sede:            "Cancha de Manco",
        nombreAdulto:    "Claudia Méndez",
        telefonoAdulto:  "11 5678-9012",
        fechaInscripcion:"18/05/2026",
        estado:          "CONFIRMADO",
    },
    {
        id: 4,
        nombreAlumno:    "Valentina Paz",
        dniAlumno:       "51.440.229",
        actividad:       "Básquet",
        sede:            "Parroquia Sagrado Corazón",
        nombreAdulto:    "Roberto Paz",
        telefonoAdulto:  "11 6789-0123",
        fechaInscripcion:"17/05/2026",
        estado:          "REVISION",
    },
    {
        id: 5,
        nombreAlumno:    "Martina García",
        dniAlumno:       "49.103.883",
        actividad:       "Hockey mixto",
        sede:            "Capilla San José Obrero",
        nombreAdulto:    "Laura García",
        telefonoAdulto:  "11 7890-1234",
        fechaInscripcion:"16/05/2026",
        estado:          "CONFIRMADO",
    },
    {
        id: 6,
        nombreAlumno:    "Nicolás Torres",
        dniAlumno:       "52.001.334",
        actividad:       "Taekwondo",
        sede:            "Capilla San José Obrero",
        nombreAdulto:    "María Torres",
        telefonoAdulto:  "11 8901-2345",
        fechaInscripcion:"15/05/2026",
        estado:          "PENDIENTE",
    },
]

export const STATS_MOCK = {
    totalAlumnos:      148,
    actividadesActivas: 7,
    cuposDisponibles:   34,
    pendientes:          6,
}

export const ALUMNOS_DETALLE_MOCK = [
  {
    id: 1,
    nombreApellido:  "Lucas Rodríguez",
    dni:             "48.220.101",
    fechaNacimiento: "15/03/2010",
    edad:            16,
    genero:          "Masculino",
    domicilio:       "Av. San Martín 1234, B° Centro",
    actividad:       "Natación",
    sede:            "Capilla San José Obrero",
    estado:          "CONFIRMADO",
    nombreAdulto:    "Ana Rodríguez",
    telefonoAdulto:  "11 3456-7890",
    obraSocial:      "OSDE",
    alergias:        "no",
    medicacion:      "no",
  },
  {
    id: 2,
    nombreApellido:  "Martina García",
    dni:             "49.103.882",
    fechaNacimiento: "22/07/2012",
    edad:            13,
    genero:          "Femenino",
    domicilio:       "Calle Rivadavia 567, B° Las Achiras",
    actividad:       "Natación",
    sede:            "Capilla San José Obrero",
    estado:          "CONFIRMADO",
    nombreAdulto:    "Laura García",
    telefonoAdulto:  "11 7890-1234",
    obraSocial:      "No",
    alergias:        "si",
    medicacion:      "no",
  },
  {
    id: 3,
    nombreApellido:  "Tomás Méndez",
    dni:             "50.008.441",
    fechaNacimiento: "08/11/2008",
    edad:            17,
    genero:          "Masculino",
    domicilio:       "Calle Antofagasta 890, B° Sarmiento",
    actividad:       "Fútbol juvenil",
    sede:            "Cancha de Manco",
    estado:          "CONFIRMADO",
    nombreAdulto:    "Claudia Méndez",
    telefonoAdulto:  "11 5678-9012",
    obraSocial:      "Swiss Medical",
    alergias:        "no",
    medicacion:      "no",
  },
  {
    id: 4,
    nombreApellido:  "Valentina Paz",
    dni:             "51.440.229",
    fechaNacimiento: "30/01/2011",
    edad:            15,
    genero:          "Femenino",
    domicilio:       "Barros Pazos 234, B° Centro",
    actividad:       "Hockey mixto",
    sede:            "Parroquia Sagrado Corazón",
    estado:          "REVISION",
    nombreAdulto:    "Roberto Paz",
    telefonoAdulto:  "11 6789-0123",
    obraSocial:      "IOMA",
    alergias:        "si",
    medicacion:      "si",
  },
  {
    id: 5,
    nombreApellido:  "Nicolás Torres",
    dni:             "52.001.334",
    fechaNacimiento: "14/05/2013",
    edad:            12,
    genero:          "Masculino",
    domicilio:       "Av. San Martín 5678, B° Las Achiras",
    actividad:       "Taekwondo",
    sede:            "Capilla San José Obrero",
    estado:          "PENDIENTE",
    nombreAdulto:    "María Torres",
    telefonoAdulto:  "11 8901-2345",
    obraSocial:      "No",
    alergias:        "no",
    medicacion:      "no",
  },
  {
    id: 6,
    nombreApellido:  "Sofía Farías",
    dni:             "49.103.883",
    fechaNacimiento: "03/09/2009",
    edad:            16,
    genero:          "Femenino",
    domicilio:       "Calle Rivadavia 890, B° Centro",
    actividad:       "Folklore",
    sede:            "Capilla San José Obrero",
    estado:          "CONFIRMADO",
    nombreAdulto:    "Jorge Farías",
    telefonoAdulto:  "11 4567-8901",
    obraSocial:      "OSDE",
    alergias:        "no",
    medicacion:      "no",
  },
]