// notificacionesMock.js
export const NOTIFICACIONES_MOCK = [
    {
        id: 1,
        tipo: "NUEVA_INSCRIPCION",
        leida: false,
        fecha: "06/06/2026 14:32",
        alumno: {
        id: 7,
        nombreApellido: "Agustín Herrera",
        dni: "53.441.002",
        fechaNacimiento: "10/04/2012",
        edad: 14,
        genero: "Masculino",
        domicilio: "Calle Mitre 123, B° Centro",
        actividad: "Fútbol juvenil",
        sede: "Cancha de Manco",
        estado: "PENDIENTE",
        nombreAdulto: "Carlos Herrera",
        telefonoAdulto: "11 2345-6789",
        obraSocial: "OSDE",
        alergias: "no",
        medicacion: "no",
        }
    },
    {
        id: 2,
        tipo: "NUEVA_INSCRIPCION",
        leida: false,
        fecha: "06/06/2026 10:15",
        alumno: {
        id: 8,
        nombreApellido: "Lucía Romero",
        dni: "54.002.113",
        fechaNacimiento: "22/08/2013",
        edad: 12,
        genero: "Femenino",
        domicilio: "Av. Rivadavia 456, B° Sarmiento",
        actividad: "Folklore",
        sede: "Capilla San José Obrero",
        estado: "PENDIENTE",
        nombreAdulto: "Ana Romero",
        telefonoAdulto: "11 3456-7890",
        obraSocial: "No",
        alergias: "si",
        medicacion: "no",
        }
    },
    {
        id: 3,
        tipo: "NUEVA_INSCRIPCION",
        leida: true,
        fecha: "05/06/2026 18:45",
        alumno: {
        id: 9,
        nombreApellido: "Mateo Suárez",
        dni: "52.334.009",
        fechaNacimiento: "15/11/2010",
        edad: 15,
        genero: "Masculino",
        domicilio: "Calle Belgrano 789, B° Las Achiras",
        actividad: "Taekwondo",
        sede: "Capilla San José Obrero",
        estado: "CONFIRMADO",
        nombreAdulto: "Paula Suárez",
        telefonoAdulto: "11 4567-8901",
        obraSocial: "Swiss Medical",
        alergias: "no",
        medicacion: "si",
        }
    },
]